export const cardArray = [
  {
    id: 0,
    title: "Первый товар",
    price: "170 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card-img.png",
    href: "/product.html",
  },
  {
    id: 1,
    title: "Второй товар",
    price: "171 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card-img.png",
    href: "/product.html",
  },
  {
    id: 2,
    title: "Третий товар",
    price: "172 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card-img.png",
    href: "/product.html",
  },
  {
    id: 3,
    title: "Четвертый товар",
    price: "173 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card-img.png",
    href: "/product.html",
  },
  {
    id: 4,
    title: "Пятый товар",
    price: "174 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card-img.png",
    href: "/product.html",
  },
  {
    id: 5,
    title: "Шестой товар",
    price: "175 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card-img.png",
    href: "/product.html",
  },
];

export const sideArray = [
  {
    id: 0,
    title: "Доставка",
    text: " Проверка при получении и возможность бесплатно вернуть товар",
    img: "/images/001-delivery-truck.svg",
  },
  {
    id: 1,
    title: "Автотека",
    text: "Отчёт с историей авто: пробег, владельцы, сведения о  залоге, ДТП и ремонтах",
    img: "/images/002-sedan.svg",
  },
  {
    id: 2,
    title: "Онлайн-бронирование жилья",
    text: "Посуточная аренда квартир и домов: большой выбор вариантов для поездок по России",
    img: "/images/love1.svg",
  },
];
